# Generated by Django 2.2.6 on 2019-10-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191014_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.SmallIntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE'), (2, 'FOREIGN'), (3, 'COOPERATIVE'), (4, 'RURAL'), (5, 'PAYMENT')], default=0)),
                ('logo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('account_no', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
