# Generated by Django 2.2.6 on 2019-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191106_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
