# Generated by Django 2.2.6 on 2020-01-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usercontact_usersms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersms',
            old_name='recieved_date',
            new_name='received_date',
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together={('user', 'contact_number')},
        ),
        migrations.AlterUniqueTogether(
            name='usersms',
            unique_together={('user', 'sender')},
        ),
    ]
