# Generated by Django 2.2.6 on 2020-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200106_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', help_text='to verify user from firebase phone auth', max_length=100),
            preserve_default=False,
        ),
    ]
