# Generated by Django 2.2.6 on 2020-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200205_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkycdetail',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userkycdetail',
            name='gender',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE'), ('o', 'OTHER')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userkycdetail',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userkycdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userkycdetail',
            name='adhaar_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userkycdetail',
            name='adhaar_no',
            field=models.CharField(max_length=50),
        ),
    ]
