# Generated by Django 2.2.6 on 2020-07-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
