# Generated by Django 2.2.6 on 2020-06-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200630_1537'),
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserBankAccount'),
        ),
        migrations.AddField(
            model_name='reward',
            name='cashgram_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='expire_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expired_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.Offer'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (3, 'UNOPENED'), (4, 'OPENED')], default=3),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saving_goal.Transaction'),
        ),
    ]
