# Generated by Django 2.2.6 on 2020-07-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20200630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expire_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
