# Generated by Django 2.2.6 on 2020-07-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_auto_20200701_0504'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='reward',
        #     name='reward_id',
        #     field=models.CharField(max_length=20, null=True, unique=True),
        # ),
    ]
