# Generated by Django 2.2.6 on 2020-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0007_offer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
