# Generated by Django 2.2.6 on 2019-10-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0004_auto_20191012_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='savinggoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to be save', max_digits=8),
        ),
    ]
