# Generated by Django 2.2.6 on 2019-10-12 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0005_auto_20191012_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savinggoal',
            name='id',
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In Progress'), (1, 'Completed'), (2, 'Canceled'), (3, 'Withdraw')], default=0),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
