# Generated by Django 2.2.6 on 2019-10-14 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving_goal', '0006_auto_20191012_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.SmallIntegerField(choices=[(0, 'DEBIT'), (0, 'CREDIT')])),
                ('status', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (0, 'CANCELLED')], default=0)),
                ('data', models.TextField()),
                ('extra_data', models.TextField()),
                ('comment', models.TextField()),
                ('associated_pk', models.CharField(max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
