# Generated by Django 2.2.6 on 2019-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='deduction_mode',
            field=models.SmallIntegerField(choices=[('AUTO DEBIT', 1), ('MANUAL DEBIT', 0)], default=1),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='deposit_frequency',
            field=models.SmallIntegerField(choices=[('manual', 1), ('daily', 1), ('weekly', 7), ('monthly', 30)], default=0),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='last_deposited',
            field=models.DateTimeField(null=True),
        ),
    ]
