# Generated by Django 2.2.6 on 2019-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0008_auto_20191025_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoal',
            name='deposit_frequency',
            field=models.SmallIntegerField(choices=[(1, 'manual'), (1, 'daily'), (7, 'weekly'), (30, 'monthly')], default=0),
        ),
    ]
