# Generated by Django 2.2.6 on 2019-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0009_auto_20191028_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoal',
            name='deduction_mode',
            field=models.SmallIntegerField(choices=[(1, 'AUTO DEBIT'), (0, 'MANUAL DEBIT')], default=1),
        ),
    ]
