# Generated by Django 2.2.6 on 2019-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0010_auto_20191028_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (3, 'CANCELLED')], default=0),
        ),
    ]
