# Generated by Django 2.2.6 on 2019-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0011_auto_20191106_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'DEBIT'), (1, 'CREDIT')]),
        ),
    ]
