# Generated by Django 2.2.6 on 2019-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0012_auto_20191117_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='payment_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savinggoal',
            name='deposit_frequency',
            field=models.SmallIntegerField(choices=[(1, 'daily'), (7, 'weekly'), (30, 'monthly')], default=0),
        ),
    ]
