# Generated by Django 2.2.6 on 2019-12-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0013_auto_20191218_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savinggoal',
            options={'ordering': ['-created_at']},
        ),
    ]
