# Generated by Django 2.2.6 on 2020-02-25 11:21

import api.saving_goal.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0015_auto_20191230_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=api.saving_goal.utils.current_timestamp_string, max_length=20, null=True, unique=True),
        ),
    ]
