# Generated by Django 2.2.6 on 2020-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0016_transaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(4, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (3, 'CANCELLED'), (0, 'INITIATED')], default=0),
        ),
    ]
