# Generated by Django 2.2.6 on 2020-03-29 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving_goal', '0017_auto_20200225_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savinggoal',
            name='contributors',
        ),
        migrations.CreateModel(
            name='SavingGoalContributor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('saving_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_goal.SavingGoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
