# Generated by Django 2.2.6 on 2020-03-29 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving_goal', '0018_auto_20200329_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='contributors',
            field=models.ManyToManyField(null=True, through='saving_goal.SavingGoalContributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
