# Generated by Django 2.2.6 on 2019-11-17 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20191117_0341'),
        ('saving_goal', '0011_auto_20191106_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('withdraw_amount', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILED'), (3, 'CANCELLED')], default=0)),
                ('saving_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_goal.SavingGoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBankAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
