# Generated by Django 2.2.6 on 2019-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithdrawrequest',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
