# Generated by Django 2.2.6 on 2019-12-18 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving_goal', '0013_auto_20191218_1934'),
        ('payment', '0004_userwithdrawrequest_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('subscription_id', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('auth_link', models.TextField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(1, 'ACTIVE'), (0, 'PENDING')], default=0)),
                ('extra_data', models.TextField()),
                ('saving_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving_goal.SavingGoal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
