# Generated by Django 2.2.6 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_userwithdrawrequest_upi_vpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithdrawrequest',
            name='reference_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userwithdrawrequest',
            name='utr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
