# Generated by Django 2.2.6 on 2020-06-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200506_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwithdrawrequest',
            options={'ordering': ('-created_at',)},
        ),
    ]
