# Generated by Django 2.2.6 on 2019-12-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=500, upload_to='aspirations')),
                ('appreciation', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be save', max_digits=8)),
                ('target_date', models.DateTimeField(help_text='Specific date of an event or festival', null=True)),
                ('target_days', models.SmallIntegerField(default=0, help_text="No's of days to complete this goals")),
                ('completed', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False, help_text='Featured aspiration will be shown on top or home page as per the requirements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AspirationFollower',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspiration.Aspiration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
