# Generated by Django 2.2.6 on 2019-12-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspiration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aspiration',
            name='target_date',
            field=models.DateTimeField(blank=True, help_text='Specific date of an event or festival', null=True),
        ),
        migrations.AlterField(
            model_name='aspirationfollower',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
