# Generated by Django 2.2.6 on 2020-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0002_auto_20191230_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='icon_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aspiration',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
