# Generated by Django 2.2.6 on 2020-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspiration', '0003_auto_20200211_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspiration',
            name='icon_image',
            field=models.ImageField(max_length=500, upload_to='aspirations'),
        ),
    ]
